spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
zeemsv.datasource.igrp.url=${IGRP_DB_URL}
zeemsv.datasource.igrp.username=${IGRP_DB_USERNAME}
zeemsv.datasource.igrp.password=${IGRP_DB_PASSWORD}
zeemsv.datasource.igrp.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=INFO
