spring.application.name=zeemsv-api
spring.profiles.active=dev
server.port=8086
server.servlet.context-path=/zeemsv-api

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.out-of-order=true
spring.flyway.schemas=public
spring.flyway.locations=classpath:db/migration

# BD principal (db_zeemsv)
spring.datasource.url=jdbc:postgresql://localhost:5432/db_zeemsv
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# BD secundaria IGRP (zeemsv_igrp_db)
zeemsv.datasource.igrp.url=jdbc:postgresql://localhost:5432/zeemsv_igrp_db
zeemsv.datasource.igrp.username=postgres
zeemsv.datasource.igrp.password=postgres
zeemsv.datasource.igrp.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger-ui.html
management.endpoints.web.exposure.include=health,info

spring.jackson.property-naming-strategy=SNAKE_CASE

## APPLICATION configuration
application.autentika.user-info-url=https://dev-iam.devtrust.cv/realms/zeemsv-realm/protocol/openid-connect/userinfo
application.session.jwt-secret=oeirtewryewyuytiti-rtiutio5uyiut-6touttuorttrorto-rtrouottyouier
application.session.jwt-expiration-in-hours=3
application.session.otp-expiration-in-minutes=5

application.minio.url=http://62.84.179.137:9003
application.minio.access-key=GkZ4vNA7OPqsMN99Eh73
application.minio.secret-key=hD4bPlGfGCjPCQ77HSVVs9Laso8swvRPOxZvwq9S
application.minio.bucket-name=igrp-zeemsv
application.docs.public-viewer-url=

### Firebase configuration file for authentication
firebase.config-path=/opt/devops/zeemsv-api/firebase-adminsdk-keys.json

firebase.config.base64=ew0KICAidHlwZSI6ICJzZXJ2aWNlX2FjY291bnQiLA0KICAicHJvamVjdF9pZCI6ICJzaWdzZS1kZXYiLA0KICAicHJpdmF0ZV9rZXlfaWQiOiAiZGZhOGU5ZWE0ZmQ4NGVmMDRlZjUzZjI2MmJjNGY5NmY1ZWEwYTUxMSIsDQogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ3ZraTRnLzRycExVOGpcbkY3NVRUSzFGcEhHemRSWXp1dDNlOXA3eGZPM3lmc0ZweDVMUDZteEhOZ0FoeGxNTjkrK2djMjM4S0FxQ3dFTUNcbkRBbThDS1BzdGVUaW1OKzdxczY4KzFqTGk0VTZEcVN1bWkyaGN4azB0Z04wNHBhZ05xaC9YMWNvUW8rc3E0UFZcbnZWNUpiZkNvS2ppOTNaa29hdzJwSktVN0hML3AvbFQrY2I5ZVlHQWRxa1JnUTc3UFErdlp3KzVqZm8zUThXU01cbjNqVFp4K055N253TVVkVEdLM1Z2TUx6Y2pjMW1WeThPbVZYYVFrVGI4cnNMM3ZIQlRicnI2QllmbkpuN0IvQjNcbkxoQU0xQ2ZuUjJaY09pTDRpbUFSSFZRU1RLVEp0dlk1U3FMM3BENXFRZXNXckRlMVlORHVuY25IeFNjcFExMmNcbmRoS2I4N2tsQWdNQkFBRUNnZ0VBRHBKNytLb3RIZWh3VXBIVWJyYUZCU3crY2E0c3J4TjUrZGtQWFN6STFTRTNcbkxXL3VuQW94ZllHYVpqTS9Ubi8vS0JxY2pOckg4STFEb29aY1FucVhISDBHWjlaWGI0eWdSeWczZVFGMkI5a1NcblN4bXA0dVlhTi9sSmRTaWZadUhTZjJ2cTRJRVJ5cnVib0NCdEZId25CdFltU24vN2g5TEcyZnljS0RsZEptOGRcbjQxaU5zTmNPd3U3ZTZTWHRDU0dteG5GNEhnaVg5NkRINVJrNEtYYnY1dU5FbVkxT3A2aGVLVGl2QTR3amFCQTBcbitSYXc0SjJtazRxN1c2bGRPeE5jUDZ0aHIyMm1yTzVGZUtIZGQ0YUxid0VQNmpwSEozclVCTGhrOUNISWZuQVBcbkFSUlUrSTFmYUlMQWNZamFlcHhFYjQ5OUhiVlBvV0Z0dHNyTW1pNkhTd0tCZ1FEZXkxcUkzcm43NHd5eGlxa1FcbjR2Si92TThXOEVEZXpaY2dKWDFkYnFIRTRjdVBjbUIvb1FFUnk2d1laMGo5Qm11dm4zQjJNaTNUMmc2eTJBY3ZcbkU4RldFbXZ6OUJvc0VQMGhoZDcxamRkWlJLdWVPaS9UcllXc3JDQitIN2dSVERDWkl5dGIrdkE1d2JjQ3hVZG1cbjlCN0t6WkthWlFBWUR5SklpU21aMzNIaXR3S0JnUURKdlFrWG0wKzRUc2FldDRuZWcxdkJ6NGFwOXFlbGN1ZDBcbm9DMloyZTVQRE51QnFLZUJHcE5IS1UxdEg5MlZSd1NtdmRkdXRzOHQwTkFiQWw1MTA1NURQcnd4ZVhRcUVaLzBcbnd5dlpPWCtNN3NmS0pKNmlneGhOZWhsOUwyd0FkR1JqQW9jd3UxRDV4TXZuWXdGR3VHd0dqNDB3VVZ3ZG9yUW1cbmRHKzZGWjEzQXdLQmdDUmpjbFlJaXJmcFRabHgzRXMxeGdXM0FOdnVRYW9pU2h5bUF1UFB2Znc2Sk5VNUNTblBcblVpMWw1cVhWdU1ZYTFsdkkzc1Z2VEt6ZFlLazFQM2NnOHVMci8xWEkrTDFaeVA1QXJ6bk1BUEJEbHdRdzNMN21cbkNIODdYZE03dXdTWVBSZkY5cjcvTFYxQmxuS05aaXdha3l6c2hwVlJDY0xrTmVWREFkaHY5bG5oQW9HQkFMMFBcbjd2Unp0b3VKTURWUTF1RjFBOG9uM2hGdE9vSWdwRysxS2VkVXlUVEdYUFV2aFFQR1R4NVN3K0F3Qys2NVpzK0pcbmZOdWljWm1EWjNUWWpJUXFOZGpaYzI5K1huS0tuL2kzN0dFZ3RMdjBqOEtPL1NoYWFhMDZiNmJWaVljSGpZa0lcbnRuL2lIS3BuVjV6Yk9UZjQ0Q3hwM2l6Wkl0WVhSSFFCalMrODBCelhBb0dCQUpBSkxZWm9ZYldmaHQ5NjNubm5cbkFMbVBGUVJyV25mU0NpQ3dSRU5QSWtUQTV5V3Q5QmZRNHVjQnc4YTlqMlB4SERNMXVNemRybmFCMmhaNW1TSWxcbnVSaTJuQi9JL1drcHNab0RsQmMzVTE4MEhjeUJPTkdUTDUrdzVsMERsQm4rMmFLdU1WaHBQNlJJaVlBTVg2aFpcbnJ2V2JLQllrMnU4amNnRGhKVFRQSmJyUlxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwNCiAgImNsaWVudF9lbWFpbCI6ICJmaXJlYmFzZS1hZG1pbnNkay1mYnN2Y0BzaWdzZS1kZXYuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLA0KICAiY2xpZW50X2lkIjogIjEwMjU2NDcwMDg4ODc5MDk3NjAyMyIsDQogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsDQogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLA0KICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsDQogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2ZpcmViYXNlLWFkbWluc2RrLWZic3ZjJTQwc2lnc2UtZGV2LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwNCiAgInVuaXZlcnNlX2RvbWFpbiI6ICJnb29nbGVhcGlzLmNvbSINCn0NCg0Kz

## OPENAI
application.openapi.server-url=http://localhost:8086/zeemsv-api
application.openapi.force-https-hosts=localhost

zeemsv.integration.enabled=true

## PESQUISA CNI
zeemsv.integration.pesquisa-cni.enabled=true
zeemsv.integration.pesquisa-cni.url=https://gateway-pdex.gov.cv/t/sniac.gov/PesquisaDoSNIAC/1.0/pesquisaDocumentoSNIAC
zeemsv.integration.pesquisa-cni.authorization=eyJ4NXQiOiJNRGd4WkRNd09XTmxZV0kxTUdVNVlUQTVORE15TlRjMU1XRmtabVV4WVRRell6RTROelZtTnpkaU9EVm1Zemd3TVdNeFlqQTFaV1l6TW1NMk1tVmtNZyIsImtpZCI6Ik1EZ3haRE13T1dObFlXSTFNR1U1WVRBNU5ETXlOVGMxTVdGa1ptVXhZVFF6WXpFNE56Vm1OemRpT0RWbVl6Z3dNV014WWpBMVpXWXpNbU0yTW1Wa01nX1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJkZ2VmcGVwQG1mLmdvdi5jdkBzbmlhYy5nb3YiLCJhdXQiOiJBUFBMSUNBVElPTiIsImF1ZCI6IjhpSjVyalMxUjMwX2FmNlZ4OE93Y09GbEN6a2EiLCJuYmYiOjE3NDI4MjUxNjMsImF6cCI6IjhpSjVyalMxUjMwX2FmNlZ4OE93Y09GbEN6a2EiLCJzY29wZSI6ImRlZmF1bHQiLCJpc3MiOiJodHRwczpcL1wvbG9jYWxob3N0Ojk0NDNcL29hdXRoMlwvdG9rZW4iLCJleHAiOjkyMjMzNzIwMzY4NTQ3NzUsImlhdCI6MTc0MjgyNTE2MywianRpIjoiZTAwNTNjYTQtYmZkZi00MTRiLWJlMGYtYjNkNThmNGIzMThhIn0.qFTD9IeiAC8m54hfU8epY5LRnQn5Jd2CZwLerhGX8zXWxQFsI0wo1sZn20ibTwvxUOqTzfmqOoFTmovKUun0Jlg5IPwMozaA2HEFuAmCF5n5JKz6-9aIAP9uROG4DF2dzmATgDsPRDoCcpdyAOor2SKm5KF5T_nmfET1cdEAhQubt67ww-PxWcTFvN2TW2NiwpwjVq5zJNMUS-xVOV-0fyetwlSGsHaYWHiH4hkk04ykrCaCWDmW2STAGanqoECDHCFQXmJ1MTsMkBKzgmGQ0iRDtFw3E_AiQQVH2E-UaYDf187zfyuVrN_Lh5hDaS2XQs8GFUe5PbXr78IfleDZYQ
zeemsv.integration.pesquisa-cni.authorization-header=eyJ4NXQiOiJNRGd4WkRNd09XTmxZV0kxTUdVNVlUQTVORE15TlRjMU1XRmtabVV4WVRRell6RTROelZtTnpkaU9EVm1Zemd3TVdNeFlqQTFaV1l6TW1NMk1tVmtNZyIsImtpZCI6Ik1EZ3haRE13T1dObFlXSTFNR1U1WVRBNU5ETXlOVGMxTVdGa1ptVXhZVFF6WXpFNE56Vm1OemRpT0RWbVl6Z3dNV014WWpBMVpXWXpNbU0yTW1Wa01nX1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJkZ2VmcGVwQG1mLmdvdi5jdkBzbmlhYy5nb3YiLCJhdXQiOiJBUFBMSUNBVElPTiIsImF1ZCI6IjhpSjVyalMxUjMwX2FmNlZ4OE93Y09GbEN6a2EiLCJuYmYiOjE3NDI4MjUxNjMsImF6cCI6IjhpSjVyalMxUjMwX2FmNlZ4OE93Y09GbEN6a2EiLCJzY29wZSI6ImRlZmF1bHQiLCJpc3MiOiJodHRwczpcL1wvbG9jYWxob3N0Ojk0NDNcL29hdXRoMlwvdG9rZW4iLCJleHAiOjkyMjMzNzIwMzY4NTQ3NzUsImlhdCI6MTc0MjgyNTE2MywianRpIjoiZTAwNTNjYTQtYmZkZi00MTRiLWJlMGYtYjNkNThmNGIzMThhIn0.qFTD9IeiAC8m54hfU8epY5LRnQn5Jd2CZwLerhGX8zXWxQFsI0wo1sZn20ibTwvxUOqTzfmqOoFTmovKUun0Jlg5IPwMozaA2HEFuAmCF5n5JKz6-9aIAP9uROG4DF2dzmATgDsPRDoCcpdyAOor2SKm5KF5T_nmfET1cdEAhQubt67ww-PxWcTFvN2TW2NiwpwjVq5zJNMUS-xVOV-0fyetwlSGsHaYWHiH4hkk04ykrCaCWDmW2STAGanqoECDHCFQXmJ1MTsMkBKzgmGQ0iRDtFw3E_AiQQVH2E-UaYDf187zfyuVrN_Lh5hDaS2XQs8GFUe5PbXr78IfleDZYQ
zeemsv.integration.pesquisa-cni.authorization-scheme=Bearer

##PESQUISA NIF
zeemsv.integration.pesquisa-nif.enabled=true
zeemsv.integration.pesquisa-nif.url=https://gateway-pdex.gov.cv/consultanif/1.0.0/detalhesPessoaOp
zeemsv.integration.pesquisa-nif.authorization=eyJ4NXQiOiJZbUkwTlRrek5tUXdZMlU0WXpVMVlqWmxZemN6TUdabFlqUTFNRGc1T1dObE5UYzRaR0kwTWpCbU1tVmlPR013TXpNMllUazVPVEZrTW1VMlpUZGpOUSIsImtpZCI6IlltSTBOVGt6Tm1Rd1kyVTRZelUxWWpabFl6Y3pNR1psWWpRMU1EZzVPV05sTlRjNFpHSTBNakJtTW1WaU9HTXdNek0yWVRrNU9URmtNbVUyWlRkak5RX1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJnZXJhbGFjcmVkaXRhY2FvQG1mLmdvdi5jdkBjYXJib24uc3VwZXIiLCJhdXQiOiJBUFBMSUNBVElPTiIsImF1ZCI6IjVwZnpRWFlYaXF0QmZObWJNVlhOMHNsaEdVa2EiLCJuYmYiOjE3NzAxMzg0MTQsImF6cCI6IjVwZnpRWFlYaXF0QmZObWJNVlhOMHNsaEdVa2EiLCJzY29wZSI6ImRlZmF1bHQiLCJpc3MiOiJodHRwczpcL1wvbG9jYWxob3N0Ojk0NDNcL29hdXRoMlwvdG9rZW4iLCJleHAiOjkyMjMzNzIwMzY4NTQ3NzUsImlhdCI6MTc3MDEzODQxNCwianRpIjoiOGJiZGNlMzItZmFjZi00MDA5LWE1MzAtYjE4NmFhNDc1MGJiIn0.vu2KBv0s5lCPwBVU8PCt64MIcuMbmm22xjJxl20xizbsNHfEj6jDS8Re8npXjks-T1ZUOyJnp-Bwrd2JZvPIsnABknRiyWDoO0eH5lfQh9qnLL1j0NMA4BbrB4jKa63GgJ0rKpZXCcd43AfFEY_o8dqF9ZXOKconYuGm4Ne6PLwwmfP0H4jyJfzi_66p2WkV6-j2oiJ_olPksPzzNm2g9sqS4-9v0P2lSCbcR1st1GD_G4RaD8UWsC0neD7lm-uY0-G__EyfTl3_m2YomQEDF5gcA9q7nxfuun6U1SCcg47dPA4ava1K-UHY8zlSoMH8EY0bSJYwLNnOPJiEepLdjw

## PESQUIA SIRC
zeemsv.integration.pesquisa-sirc.enabled=true
zeemsv.integration.pesquisa-sirc.url=
zeemsv.integration.pesquisa-sirc.authorization=
zeemsv.integration.pesquisa-sirc.nif-param=P_NIF


zeemsv.security.jwt-secret=change-me

## EMAIL CONFIG
application.mail.enabled=true
application.mail.from=no-reply@zeemsv.cv
application.mail.otp-subject=Codigo de verificacao ZEEMSV
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=devtrust.dev@gmail.com
spring.mail.password=zpfy itom abrh eanq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

