spring.application.name=zeemsv-api
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
server.port=${SERVER_PORT:8086}
server.servlet.context-path=${SERVER_CONTEXT_PATH:/zeemsv-api}

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=${FLYWAY_ENABLED:false}
spring.flyway.schemas=public
spring.flyway.locations=classpath:db/migration

# BD principal (db_zeemsv)
spring.datasource.url=jdbc:postgresql://localhost:5432/db_zeemsv
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# BD secundaria IGRP (zeemsv_igrp_db)
zeemsv.datasource.igrp.url=${IGRP_DB_URL:jdbc:postgresql://localhost:5432/zeemsv_igrp_db}
zeemsv.datasource.igrp.username=${IGRP_DB_USERNAME:postgres}
zeemsv.datasource.igrp.password=${IGRP_DB_PASSWORD:postgres}
zeemsv.datasource.igrp.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger-ui.html
management.endpoints.web.exposure.include=health,info

spring.jackson.property-naming-strategy=SNAKE_CASE
