spring.datasource.url=jdbc:postgresql://localhost:5432/db_zeemsv
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
zeemsv.datasource.igrp.url=jdbc:postgresql://localhost:5432/zeemsv_igrp_db
zeemsv.datasource.igrp.username=postgres
zeemsv.datasource.igrp.password=postgres
zeemsv.datasource.igrp.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
