create table if not exists public.zee_t_solic_onboarding (
    id integer generated by default as identity primary key,
    id_tp_solic integer not null,
    dm_tipo_onboarding varchar(50),
    user_registo varchar(100),
    data_registo date,
    constraint fk_zee_t_solic_onboarding_tp_solic
        foreign key (id_tp_solic)
        references public.zee_t_tp_solicitacao (id)
);

alter table if exists public.zee_t_solic_onboarding
    add column if not exists id_tp_solic integer,
    add column if not exists dm_tipo_onboarding varchar(50),
    add column if not exists user_registo varchar(100),
    add column if not exists data_registo date;

do $$
begin
    if not exists (
        select 1
        from information_schema.table_constraints
        where constraint_schema = 'public'
          and table_name = 'zee_t_solic_onboarding'
          and constraint_name = 'fk_zee_t_solic_onboarding_tp_solic'
    ) then
        alter table public.zee_t_solic_onboarding
            add constraint fk_zee_t_solic_onboarding_tp_solic
            foreign key (id_tp_solic)
            references public.zee_t_tp_solicitacao (id);
    end if;
end $$;
