create table if not exists public.zee_t_pedido_acesso_investidor (
    id integer generated by default as identity primary key,
    id_utilizador integer not null,
    id_investidor integer not null,
    dm_tp_representante varchar(50),
    ficheiro_compravativo varchar(255),
    dm_estado varchar(50),
    obs varchar(1000),
    data_registo date not null,
    data_resposta date,
    user_resposta varchar(100)
);

alter table if exists public.zee_t_pedido_acesso_investidor
    add column if not exists id_utilizador integer,
    add column if not exists id_investidor integer,
    add column if not exists dm_tp_representante varchar(50),
    add column if not exists ficheiro_compravativo varchar(255),
    add column if not exists dm_estado varchar(50),
    add column if not exists obs varchar(1000),
    add column if not exists data_registo date,
    add column if not exists data_resposta date,
    add column if not exists user_resposta varchar(100);

create unique index if not exists ux_zee_t_pedido_acesso_investidor_utilizador_investidor
    on public.zee_t_pedido_acesso_investidor (id_utilizador, id_investidor);
